.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH gnuclad 1 "FEBRUARY 2011" "gnuclad 0.2.4 and higher" "gnuclad man page"
.SH NAME
gnuclad \- a cladogram generator
.SH SYNOPSIS
.B gnuclad
.I input-file output-file
.B [
.I config-file
.B ]
.br
.B gnuclad
.I input-file output-format
.B [
.I config-file
.B ]
.SH DESCRIPTION
.B gnuclad
reads the input file, computes a cladogram and writes
the results into the output file. If an output file is
specified instead of a format, the output format
is guessed from the file name extension.
For a list of supported input/output formats, please
consult the gnuclad TeXinfo manual.
.SH OPTIONS
.IP "config-file"
Use an alternate
.I config-file
instead of the built-in defaults.
.SH DIAGNOSTICS
The exit status is 0 if execution was successful
(even with warnings) and 1 if an error has occured.

The following diagnostics may be issued:
 
Error:
.RS
A description of the error
.RE
Warning:
.RS
A description of the warning

.SH BUGS
Please report bugs to
https://bugs.launchpad.net/gnuclad
.SH AUTHOR
Donjan Rodic <donjan at dyx dot ch>
.SH "SEE ALSO"
The full documentation for
.B gnuclad
is maintained as a TeXinfo manual. If the
.B info
and
.B gnuclad
programs are properly installed at your site, the
command
.IP
.B info gnuclad
.PP
should give you access to the complete manual.
