@c Part of the gnuclad texinfo manual

@defindex gc

@node Programming
@chapter Programming

Here's a small documentation if you wish to hack gnuclad.
Patches are always welcome. New parsers/generators even more so!

@menu
* Classes and utilities::
* Configuration Options::
* Writing a parser::
* Writing a generator::
@end menu

@include gnuclad-programming-classes.texi
@include gnuclad-programming-config.texi
@include gnuclad-programming-parser.texi
@include gnuclad-programming-generator.texi

