@c Part of the gnuclad texinfo manual


@node Configuration Options
@unnumberedsec



@section Adding configuration options

When adding a configuration option, be sure to implement it at least in the
following places:
@itemize @bullet
@item src/gnuclad.h: members of the Cladogram class (declaration)
@item src/gnuclad-cladogram.cpp: in the constructor of the Cladogram object
                                 (initialisation / default setting)
@item src/gnuclad-cladogram.cpp: in the parseOptions function
@item src/generator/conf.cpp: output and description of the new option
@item doc/src/gnuclad-config.texi: at the bottom, insert the new config file
                                   created by using 'conf' as output
@item third party gnuclad configuration files you have access to
@end itemize



@section Using configuration options

The options are usually read by a separate configuration parser, but can be
modified by the data input parser if necessary and should be implemented by the
generator as completely as possible.
The option names in the config file are identical to the variable names and can
be accessed via the cladogram pointer:
@example
int myTextSize = clad->labelFontSize;
clad->monthsInYear = 10;
@end example

In order to work with the most current options, open the 'gnuclad.h' header file
and search for CONFIG OPTIONS. This will take you straight to the declarations.

You can also look at the @ref{Config Options,,Config Options} chapter
for a more detailed explanation.

